export const TROMBONE_URLS = {
  "A#1": "/assets/trombone/As1.ogg",
  "A#2": "/assets/trombone/As2.ogg",
  "A#3": "/assets/trombone/As3.ogg",
  C3: "/assets/trombone/C3.ogg",
  C4: "/assets/trombone/C4.ogg",
  "C#2": "/assets/trombone/Cs2.ogg",
  "C#4": "/assets/trombone/Cs4.ogg",
  D3: "/assets/trombone/D3.ogg",
  D4: "/assets/trombone/D4.ogg",
  "D#2": "/assets/trombone/Ds2.ogg",
  "D#3": "/assets/trombone/Ds3.ogg",
  "D#4": "/assets/trombone/Ds4.ogg",
  F2: "/assets/trombone/F2.ogg",
  F3: "/assets/trombone/F3.ogg",
  F4: "/assets/trombone/F4.ogg",
  "G#2": "/assets/trombone/Gs2.ogg",
  "G#3": "/assets/trombone/Gs3.ogg",
};
